name: Publish package to GitHub Packages

on:
  push:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Publish package (Snapshot)
        if: github.event_name == "push"
        run: mvn --batch-mode deploy -PSnapshotsPackages
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      - name: Publish package
        if: github.event_name == "release"
        run: mvn --batch-mode deploy -PReleasePackages
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}